/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getRemoteImageDimensionsResult(): Promise<[number, number]>

export declare function imageDimensions(path: string): [number, number]
